#Description of controller invocation from ros_controller package by controller manager. 

sbot:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 100
    position:
      Joint1:
        type: effort_controllers/JointPositionController
        joint: Joint1
        pid: {p: 20.0, i: 0.3, d: 10.0, i_clamp: 1.0}
      Joint2:
        type: effort_controllers/JointPositionController
        joint: Joint2
        pid: {p: 20.0, i: 0.0, d: 10.0, i_clamp: 1.0}
 
